Repository AICoE/learn-katacoda, pull requests merged in 2020-03, with the labels that each got.

#7 Suppress xtrace for set-env.sh [prom-api]
  ai-machine-learning/prometheus-api-client/assets/setup.sh
  ai-machine-learning/prometheus-api-client/index.json
  ai-machine-learning/prometheus-api-client/set-env.sh
Labels: approved

#19 [Prom-api]Add imagestream for pre-built notebook image
  ai-machine-learning/prometheus-api-client/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-api-client/assets/notebook-imagestream.yaml
  ai-machine-learning/prometheus-api-client/assets/setup.sh
  ai-machine-learning/prometheus-api-client/env-init.sh
  ai-machine-learning/prometheus-api-client/index.json
Labels: approved, size/M

#20 Update notebook description
  ai-machine-learning/prometheus-api-client/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-api-client/assets/02-jupyter-notebook-list.png
Labels: approved

#22 Add Prometheus time series forecasting scenario
  ai-machine-learning-pathway.json
  ai-machine-learning/prometheus-timeseries-forecasting/01-loading-the-notebook-images.md
  ai-machine-learning/prometheus-timeseries-forecasting/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-timeseries-forecasting/03-accessing-the-web-console.md
  ai-machine-learning/prometheus-timeseries-forecasting/assets/01-components-time-series.png
  ai-machine-learning/prometheus-timeseries-forecasting/assets/01-time-series-forecasting.png
  ai-machine-learning/prometheus-timeseries-forecasting/assets/02-jupyter-notebook-list.png
  ai-machine-learning/prometheus-timeseries-forecasting/assets/02-jupyter-secret.png
  ai-machine-learning/prometheus-timeseries-forecasting/assets/03-openshift-console-page.png
  ai-machine-learning/prometheus-timeseries-forecasting/assets/03-openshift-login-page.png
  ai-machine-learning/prometheus-timeseries-forecasting/assets/notebook-imagestream.yaml
  ai-machine-learning/prometheus-timeseries-forecasting/assets/setup.sh
  ai-machine-learning/prometheus-timeseries-forecasting/finish.md
  ai-machine-learning/prometheus-timeseries-forecasting/index.json
  ai-machine-learning/prometheus-timeseries-forecasting/intro.md
  ai-machine-learning/prometheus-timeseries-forecasting/set-env.sh
Labels: approved, size/L

#23 Add deploy-prometheus-grafana scenario in introduction
  assets/introduction/deploy-prometheus-grafana/01-demo-app-home-page.png
  assets/introduction/deploy-prometheus-grafana/01-demo-app-metrics-page.png
  assets/introduction/deploy-prometheus-grafana/02-prometheus-targets-page.png
  assets/introduction/deploy-prometheus-grafana/03-grafana-add-ds-page.png
  assets/introduction/deploy-prometheus-grafana/03-grafana-add-prom-ds-page.png
  assets/introduction/deploy-prometheus-grafana/03-grafana-login-page.png
  assets/introduction/deploy-prometheus-grafana/03-grafana-password-change-page.png
  assets/introduction/deploy-prometheus-grafana/03-grafana-welcome-page.png
  assets/introduction/deploy-prometheus-grafana/04-grafana-1-panel-dashboard-page.png
  assets/introduction/deploy-prometheus-grafana/04-grafana-2-panel-dashboard-page.png
  assets/introduction/deploy-prometheus-grafana/04-grafana-create-dashboard-page.png
  assets/introduction/deploy-prometheus-grafana/04-grafana-create-panel-page.png
  introduction/deploy-prometheus-grafana/1deploy-demo-app.md
  introduction/deploy-prometheus-grafana/2deploy-prometheus.md
  introduction/deploy-prometheus-grafana/3deploy-grafana.md
  introduction/deploy-prometheus-grafana/4create-dashboard.md
  introduction/deploy-prometheus-grafana/assets/deploy-prometheus.yaml
  introduction/deploy-prometheus-grafana/assets/volumes.json
  introduction/deploy-prometheus-grafana/env-init.sh
  introduction/deploy-prometheus-grafana/finish.md
  introduction/deploy-prometheus-grafana/index.json
  introduction/deploy-prometheus-grafana/intro.md
  introduction/deploy-prometheus-grafana/set-env.sh
  ml-prometheus-metrics-pathway.json
Labels: approved, size/XL

#24 Update ml-prometheus pathway
  ml-prometheus-metrics-pathway.json
Labels: approved

#25 Fix Image Asset location
  ai-machine-learning/prometheus-api-client/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-api-client/03-accessing-the-web-console.md
  ai-machine-learning/prometheus-timeseries-forecasting/01-loading-the-notebook-images.md
  ai-machine-learning/prometheus-timeseries-forecasting/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-timeseries-forecasting/03-accessing-the-web-console.md
  assets/ai-machine-learning/prometheus-api-client/02-jupyter-notebook-list.png
  assets/ai-machine-learning/prometheus-api-client/02-jupyter-secret.png
  assets/ai-machine-learning/prometheus-api-client/02-prometheus-console.png
  assets/ai-machine-learning/prometheus-api-client/03-openshift-console-page.png
  assets/ai-machine-learning/prometheus-api-client/03-openshift-login-page.png
  assets/ai-machine-learning/prometheus-timeseries-forecasting/01-components-time-series.png
  assets/ai-machine-learning/prometheus-timeseries-forecasting/01-time-series-forecasting.png
  assets/ai-machine-learning/prometheus-timeseries-forecasting/02-jupyter-notebook-list.png
  assets/ai-machine-learning/prometheus-timeseries-forecasting/02-jupyter-secret.png
  assets/ai-machine-learning/prometheus-timeseries-forecasting/03-openshift-console-page.png
  assets/ai-machine-learning/prometheus-timeseries-forecasting/03-openshift-login-page.png
Labels: approved
