Repository AICoE/learn-katacoda, pull requests merged in 2020-04, with the labels that each got.

#27 [ai/prom-api] Update workshop instructions and title
  ai-machine-learning/prometheus-api-client/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-api-client/03-accessing-the-web-console.md
  ai-machine-learning/prometheus-api-client/index.json
  ml-prometheus-metrics-pathway.json
Labels: approved, size/M

#28 Update scenario instructions
  ai-machine-learning/prometheus-timeseries-forecasting/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-timeseries-forecasting/03-accessing-the-web-console.md
Labels: approved, size/S

#21 Thoth s2i advise
  ai-machine-learning-pathway.json
  ai-machine-learning/thoth-s2i-advise/app.md
  ai-machine-learning/thoth-s2i-advise/deploy.md
  ai-machine-learning/thoth-s2i-advise/env-init.sh
  ai-machine-learning/thoth-s2i-advise/finish.md
  ai-machine-learning/thoth-s2i-advise/index.json
  ai-machine-learning/thoth-s2i-advise/intro.md
  ai-machine-learning/thoth-s2i-advise/parameter.md
  ai-machine-learning/thoth-s2i-advise/set-env.sh
  ai-machine-learning/thoth-s2i-advise/setup.md
Labels: approved, size/L

#30 Move PAD workshop pathway file to training/ dir
  training/ml-prometheus-metrics-pathway.json
Labels: approved, size/XS

#31 Revert "Move PAD workshop pathway file to training/ dir"
  ml-prometheus-metrics-pathway.json
Labels: size/XS

#32 Move pathway file to training/ dir
  training/ml-prometheus-metrics-pathway.json
Labels: approved, size/XS

#33 Add deploy-prometheus-grafana in introduction pathway
  introduction-pathway.json
Labels: approved, size/XS

#34 Update time series forecasting scenario instructions
  ai-machine-learning/prometheus-timeseries-forecasting/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-timeseries-forecasting/03-accessing-the-web-console.md
  assets/ai-machine-learning/prometheus-timeseries-forecasting/02-jupyter-notebook-list.png
Labels: approved, size/S

#35 Update instructions for intro/setup-prom-grafana scenario
  introduction/deploy-prometheus-grafana/1deploy-demo-app.md
  introduction/deploy-prometheus-grafana/2deploy-prometheus.md
  introduction/deploy-prometheus-grafana/3deploy-grafana.md
  introduction/deploy-prometheus-grafana/4create-dashboard.md
  introduction/deploy-prometheus-grafana/finish.md
  introduction/deploy-prometheus-grafana/index.json
  introduction/deploy-prometheus-grafana/intro.md
Labels: size/L

#29 Thoth Thamos CLI
  ai-machine-learning-pathway.json
  ai-machine-learning/thoth-thamos/advise.md
  ai-machine-learning/thoth-thamos/finish.md
  ai-machine-learning/thoth-thamos/index.json
  ai-machine-learning/thoth-thamos/intro.md
  ai-machine-learning/thoth-thamos/set-env.sh
  ai-machine-learning/thoth-thamos/setup.md
Labels: approved, size/L

#37 Add feedback survey link to time series scenario
  ai-machine-learning/prometheus-timeseries-forecasting/finish.md
Labels: approved, size/M

#38 Move pathway file to training/ dir
  training/ml-prometheus-metrics-pathway.json
Labels: approved, size/XS

#39 Added feedback links and removed env desc
  ai-machine-learning/thoth-s2i-advise/finish.md
  ai-machine-learning/thoth-s2i-advise/intro.md
  ai-machine-learning/thoth-s2i-provenance/finish.md
  ai-machine-learning/thoth-s2i-provenance/intro.md
  ai-machine-learning/thoth-thamos/finish.md
Labels: approved, size/M

#40 Update instructions for ai/prom-api-client scenario
  ai-machine-learning/prometheus-api-client/02-loading-the-notebook-templates.md
  ai-machine-learning/prometheus-api-client/03-accessing-the-web-console.md
  ai-machine-learning/prometheus-api-client/finish.md
  ai-machine-learning/prometheus-api-client/intro.md
  assets/ai-machine-learning/prometheus-api-client/02-prometheus-console-data.png
  assets/ai-machine-learning/prometheus-api-client/03-openshift-console-page.png
  introduction/deploy-prometheus-grafana/finish.md
  introduction/deploy-prometheus-grafana/intro.md
Labels: approved, size/M

#41 Renamed to thoth-cli
  ai-machine-learning-pathway.json
  ai-machine-learning/thoth-cli/advise.md
  ai-machine-learning/thoth-cli/finish.md
  ai-machine-learning/thoth-cli/index.json
  ai-machine-learning/thoth-cli/intro.md
  ai-machine-learning/thoth-cli/set-env.sh
  ai-machine-learning/thoth-cli/setup.md
Labels: approved, size/XS

#42 Added mass open credits
  ai-machine-learning/thoth-cli/intro.md
  ai-machine-learning/thoth-s2i-advise/intro.md
  ai-machine-learning/thoth-s2i-provenance/intro.md
Labels: approved
